source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/rahuljaswa/Specs.git'

platform :ios, '7.0'

pod 'ActionLabel'
pod 'AFNetworking', '2.5.3'
pod 'ChatViewControllers'
pod 'DZNEmptyDataSet'
pod 'FBSDKCoreKit'
pod 'FastImageCache'
pod 'Mixpanel'
pod 'Parse'
pod 'SVProgressHUD'
pod 'SZTextView'
pod 'Touchpose'
